# Copyright The Kubeflow Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# coding: utf-8

"""
    Kubeflow Trainer OpenAPI Spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: unversioned
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from kubeflow_trainer_api.models.trainer_v1alpha1_objective import TrainerV1alpha1Objective
from kubeflow_trainer_api.models.trainer_v1alpha1_parameter import TrainerV1alpha1Parameter
from kubeflow_trainer_api.models.trainer_v1alpha1_search_algorithm import TrainerV1alpha1SearchAlgorithm
from kubeflow_trainer_api.models.trainer_v1alpha1_train_job_template_spec import TrainerV1alpha1TrainJobTemplateSpec
from typing import Optional, Set
from typing_extensions import Self

class TrainerV1alpha1OptimizationJobSpec(BaseModel):
    """
    OptimizationJobSpec defines the desired state of OptimizationJob.
    """ # noqa: E501
    num_trials: Optional[StrictInt] = Field(default=None, description="numTrials is the total number of trials to run.", alias="numTrials")
    objectives: List[TrainerV1alpha1Objective] = Field(description="objectives is the list of objectives to optimize.")
    parallel_trials: Optional[StrictInt] = Field(default=None, description="parallelTrials is the number of trials to run in parallel. Defaults to 1.", alias="parallelTrials")
    parameters: List[TrainerV1alpha1Parameter] = Field(description="parameters is the list of hyperparameters to search over.")
    search_algorithm: Optional[TrainerV1alpha1SearchAlgorithm] = Field(default=None, description="searchAlgorithm is the algorithm to use for searching over the hyperparameters.", alias="searchAlgorithm")
    train_job_template: TrainerV1alpha1TrainJobTemplateSpec = Field(description="trainJobTemplate is the template for the train job to run.", alias="trainJobTemplate")
    __properties: ClassVar[List[str]] = ["numTrials", "objectives", "parallelTrials", "parameters", "searchAlgorithm", "trainJobTemplate"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TrainerV1alpha1OptimizationJobSpec from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in objectives (list)
        _items = []
        if self.objectives:
            for _item_objectives in self.objectives:
                if _item_objectives:
                    _items.append(_item_objectives.to_dict())
            _dict['objectives'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in parameters (list)
        _items = []
        if self.parameters:
            for _item_parameters in self.parameters:
                if _item_parameters:
                    _items.append(_item_parameters.to_dict())
            _dict['parameters'] = _items
        # override the default output from pydantic by calling `to_dict()` of search_algorithm
        if self.search_algorithm:
            _dict['searchAlgorithm'] = self.search_algorithm.to_dict()
        # override the default output from pydantic by calling `to_dict()` of train_job_template
        if self.train_job_template:
            _dict['trainJobTemplate'] = self.train_job_template.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TrainerV1alpha1OptimizationJobSpec from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "numTrials": obj.get("numTrials"),
            "objectives": [TrainerV1alpha1Objective.from_dict(_item) for _item in obj["objectives"]] if obj.get("objectives") is not None else None,
            "parallelTrials": obj.get("parallelTrials"),
            "parameters": [TrainerV1alpha1Parameter.from_dict(_item) for _item in obj["parameters"]] if obj.get("parameters") is not None else None,
            "searchAlgorithm": TrainerV1alpha1SearchAlgorithm.from_dict(obj["searchAlgorithm"]) if obj.get("searchAlgorithm") is not None else None,
            "trainJobTemplate": TrainerV1alpha1TrainJobTemplateSpec.from_dict(obj["trainJobTemplate"]) if obj.get("trainJobTemplate") is not None else None
        })
        return _obj


