/*
Copyright The Kubeflow Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	trainerv1alpha1 "github.com/kubeflow/trainer/v2/pkg/apis/trainer/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// OptimizationJobLister helps list OptimizationJobs.
// All objects returned here must be treated as read-only.
type OptimizationJobLister interface {
	// List lists all OptimizationJobs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*trainerv1alpha1.OptimizationJob, err error)
	// OptimizationJobs returns an object that can list and get OptimizationJobs.
	OptimizationJobs(namespace string) OptimizationJobNamespaceLister
	OptimizationJobListerExpansion
}

// optimizationJobLister implements the OptimizationJobLister interface.
type optimizationJobLister struct {
	listers.ResourceIndexer[*trainerv1alpha1.OptimizationJob]
}

// NewOptimizationJobLister returns a new OptimizationJobLister.
func NewOptimizationJobLister(indexer cache.Indexer) OptimizationJobLister {
	return &optimizationJobLister{listers.New[*trainerv1alpha1.OptimizationJob](indexer, trainerv1alpha1.Resource("optimizationjob"))}
}

// OptimizationJobs returns an object that can list and get OptimizationJobs.
func (s *optimizationJobLister) OptimizationJobs(namespace string) OptimizationJobNamespaceLister {
	return optimizationJobNamespaceLister{listers.NewNamespaced[*trainerv1alpha1.OptimizationJob](s.ResourceIndexer, namespace)}
}

// OptimizationJobNamespaceLister helps list and get OptimizationJobs.
// All objects returned here must be treated as read-only.
type OptimizationJobNamespaceLister interface {
	// List lists all OptimizationJobs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*trainerv1alpha1.OptimizationJob, err error)
	// Get retrieves the OptimizationJob from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*trainerv1alpha1.OptimizationJob, error)
	OptimizationJobNamespaceListerExpansion
}

// optimizationJobNamespaceLister implements the OptimizationJobNamespaceLister
// interface.
type optimizationJobNamespaceLister struct {
	listers.ResourceIndexer[*trainerv1alpha1.OptimizationJob]
}
